"""Initial database setup

Revision ID: 5bef4b9ce1bf
Revises: 
Create Date: 2025-07-06 17:46:21.989066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5bef4b9ce1bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('call_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_call_sessions_days_from_surgery'), table_name='call_sessions')
    op.drop_index(op.f('idx_call_sessions_patient'), table_name='call_sessions')
    op.drop_index(op.f('idx_call_sessions_scheduled_date'), table_name='call_sessions')
    op.drop_index(op.f('idx_call_sessions_status'), table_name='call_sessions')
    op.drop_index(op.f('idx_call_sessions_surgery_type'), table_name='call_sessions')
    op.alter_column('clinical_staff', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_clinical_staff_email'), table_name='clinical_staff')
    op.drop_index(op.f('idx_clinical_staff_role'), table_name='clinical_staff')
    op.create_unique_constraint(None, 'clinical_staff', ['email'])
    op.alter_column('patients', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('patients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_patients_physician'), table_name='patients')
    op.drop_index(op.f('idx_patients_primary_phone'), table_name='patients')
    op.drop_index(op.f('idx_patients_secondary_phone'), table_name='patients')
    op.drop_index(op.f('idx_patients_surgery_date'), table_name='patients')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_patients_surgery_date'), 'patients', ['surgery_date'], unique=False)
    op.create_index(op.f('idx_patients_secondary_phone'), 'patients', ['secondary_phone_number'], unique=False)
    op.create_index(op.f('idx_patients_primary_phone'), 'patients', ['primary_phone_number'], unique=False)
    op.create_index(op.f('idx_patients_physician'), 'patients', ['primary_physician_id'], unique=False)
    op.alter_column('patients', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('patients', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'clinical_staff', type_='unique')
    op.create_index(op.f('idx_clinical_staff_role'), 'clinical_staff', ['role'], unique=False)
    op.create_index(op.f('idx_clinical_staff_email'), 'clinical_staff', ['email'], unique=False)
    op.alter_column('clinical_staff', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('idx_call_sessions_surgery_type'), 'call_sessions', ['surgery_type'], unique=False)
    op.create_index(op.f('idx_call_sessions_status'), 'call_sessions', ['call_status'], unique=False)
    op.create_index(op.f('idx_call_sessions_scheduled_date'), 'call_sessions', ['scheduled_date'], unique=False)
    op.create_index(op.f('idx_call_sessions_patient'), 'call_sessions', ['patient_id'], unique=False)
    op.create_index(op.f('idx_call_sessions_days_from_surgery'), 'call_sessions', ['days_from_surgery'], unique=False)
    op.alter_column('call_sessions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
