"""Add emergency contact field to patients

Revision ID: 785e619dee3c
Revises: 5bef4b9ce1bf
Create Date: 2025-07-06 17:47:47.862451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '785e619dee3c'
down_revision: Union[str, None] = '5bef4b9ce1bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('emergency_contact', sa.String(length=100), nullable=True, comment='Emergency contact name and phone'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'emergency_contact')
    # ### end Alembic commands ###
