"""Remove emergency_contact field from patients

Revision ID: f9f80bf16448
Revises: 785e619dee3c
Create Date: 2025-07-06 18:03:36.837211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f80bf16448'
down_revision: Union[str, None] = '785e619dee3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'emergency_contact')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('emergency_contact', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Emergency contact name and phone'))
    # ### end Alembic commands ###
